version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER={DB_USERNAME:-admin}
      - POSTGRES_PASSWORD={DB_PASSWORD:-supersecure}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - db

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      backend:
        aliases:
          - adminer

networks:
  backend:
    name: backend
